from uuid import UUID
from typing import Protocol

from tennis_scoreboard.schemas.score import Score
from tennis_scoreboard.models.models import Player, Match

class PlayerRepository(Protocol):

    def get_by_id(self, id: int) -> Player: ...

    def get_by_name(self, name: str) -> Player: ...

    def add(self, name: str) -> Player: ...

class MatchRepository(Protocol):

    def get_all(self) -> list[Match]: ...

    def get_by_uuid(self, uuid: UUID) -> Match: ...

    def get_ended_player_matches(self, player_id: int) -> list[Match]: ...

    def add(self, actor: Player, opponent: Player) -> Match: ...

    def update(self, uuid: UUID, score: Score) -> Match: ...
