[project]
name = "tennis-scoreboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TheEmpressDiadema", email = "mauhkpaffftep@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "jinja2>=3.1.6",
    "pymysql>=1.2.3",
    "pytest>=9.1.1",
    "sqlalchemy>=2.0.52",
    "types-waitress>=3.0.1.20260724",
    "waitress>=3.0.2",
]

[project.scripts]
tennis-scoreboard = "tennis_scoreboard:main"

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"
